# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\PC-Phat\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mekong_remote_sensing\MeKong_Remote_Sensing_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MekongRemoteSensingDialogBase(object):
    def setupUi(self, MekongRemoteSensingDialogBase):
        MekongRemoteSensingDialogBase.setObjectName("MekongRemoteSensingDialogBase")
        MekongRemoteSensingDialogBase.resize(1090, 468)
        MekongRemoteSensingDialogBase.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(MekongRemoteSensingDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(440, 300, 621, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius:45px;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\PC-Phat\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\mekong_remote_sensing\\../../../../../../../../../Pictures/Phim/phantich.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(80, 80))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(MekongRemoteSensingDialogBase)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 80, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius:45px;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\PC-Phat\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\mekong_remote_sensing\\../../../../../../../../../Pictures/Phim/openlayer1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(128, 80))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(MekongRemoteSensingDialogBase)
        self.label_2.setGeometry(QtCore.QRect(380, 0, 471, 71))
        self.label_2.setMinimumSize(QtCore.QSize(381, 0))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(MekongRemoteSensingDialogBase)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 190, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius:45px;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\PC-Phat\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\mekong_remote_sensing\\../../../../../../../../../Pictures/Phim/remove1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(80, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(MekongRemoteSensingDialogBase)
        self.pushButton_4.setGeometry(QtCore.QRect(760, 80, 301, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius:45px;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\PC-Phat\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\mekong_remote_sensing\\../../../../../../../../../Pictures/Phim/developing2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(100, 85))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(MekongRemoteSensingDialogBase)
        self.pushButton_5.setGeometry(QtCore.QRect(760, 190, 301, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius:45px;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\PC-Phat\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\mekong_remote_sensing\\../../../../../../../../../Pictures/Phim/developing1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(MekongRemoteSensingDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 80, 411, 311))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\PC-Phat\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\mekong_remote_sensing\\../../../../../../../../../Pictures/Phim/DBSCL.png"))
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(MekongRemoteSensingDialogBase)
        self.pushButton_6.setGeometry(QtCore.QRect(770, 410, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(MekongRemoteSensingDialogBase)
        self.pushButton_7.setGeometry(QtCore.QRect(920, 410, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:hover{    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(MekongRemoteSensingDialogBase)
        QtCore.QMetaObject.connectSlotsByName(MekongRemoteSensingDialogBase)

    def retranslateUi(self, MekongRemoteSensingDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MekongRemoteSensingDialogBase.setWindowTitle(_translate("MekongRemoteSensingDialogBase", "MeKong Remote Sensing"))
        self.pushButton.setText(_translate("MekongRemoteSensingDialogBase", " Analysis"))
        self.pushButton_3.setText(_translate("MekongRemoteSensingDialogBase", "Open Layer"))
        self.label_2.setText(_translate("MekongRemoteSensingDialogBase", "<html><head/><body><p><span style=\" font-weight:600;\">MEKONG - REMOTE - SENSING</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MekongRemoteSensingDialogBase", "Remove Layer"))
        self.pushButton_4.setText(_translate("MekongRemoteSensingDialogBase", "Merge Layer"))
        self.pushButton_5.setText(_translate("MekongRemoteSensingDialogBase", "Information"))
        self.pushButton_6.setText(_translate("MekongRemoteSensingDialogBase", "OK"))
        self.pushButton_7.setText(_translate("MekongRemoteSensingDialogBase", "Cancel"))
